# Generated by Django 5.1.6 on 2025-03-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_material",
                    models.CharField(max_length=50, verbose_name="Материал клавиш"),
                ),
                ("size", models.IntegerField(verbose_name="Размер клавиатуры")),
                (
                    "number_of_keys",
                    models.IntegerField(verbose_name="Количество клавиш"),
                ),
                (
                    "os_compatibility",
                    models.CharField(max_length=255, verbose_name="Совместимость ОС"),
                ),
                (
                    "backlight",
                    models.CharField(max_length=50, verbose_name="Подсветка"),
                ),
                (
                    "connection_interface",
                    models.CharField(
                        max_length=255, verbose_name="Интерфейст подключения"
                    ),
                ),
                ("weight", models.FloatField(verbose_name="Вес")),
                (
                    "country_of_manufacture",
                    models.CharField(
                        max_length=255, verbose_name="Страна производитель"
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Бренд")),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.CreateModel(
            name="KeyBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название клавиатуры"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Слаг"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m,%d/", verbose_name="Фото"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "is_published",
                    models.BooleanField(
                        choices=[(False, "Черновик"), (True, "Опубликовано")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(
                        default=1, verbose_name="Количество единиц на складе"
                    ),
                ),
                (
                    "equipments",
                    models.TextField(max_length=255, verbose_name="Комплектация"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category",
                        to="kb_app.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "specifications",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="kb_app.specification",
                        verbose_name="Характеристики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клавиатура",
                "verbose_name_plural": "Клавиатуры",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="kb_app_keyb_created_2455be_idx"
                    )
                ],
            },
        ),
    ]
