# Generated by Django 5.1.6 on 2025-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="name",
            field=models.CharField(
                default=None, max_length=50, verbose_name="Название клавиатуры"
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="connection_interface",
            field=models.CharField(
                max_length=255, verbose_name="Интерфейс подключения"
            ),
        ),
    ]
