# Generated by Django 5.1.6 on 2025-03-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb_app", "0002_specification_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyboard",
            name="price",
            field=models.IntegerField(
                default=0, verbose_name="Стоимость за единицу товара"
            ),
        ),
    ]
