name: Run test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4

      - name: Install dependencies
        run: |
          poetry install --no-cache

      - name: Run linter
        run: |
          poetry run test